<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRrbvrbf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRrbvrbf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRrbvrbf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRrbvrbf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRrbvrbf\appDevDebugProjectContainer([
    'container.build_hash' => 'Rrbvrbf',
    'container.build_id' => '91cfa5b8',
    'container.build_time' => 1557208719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRrbvrbf');
