<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.lllhbbu' shared service.

return $this->services['service_locator.lllhbbu'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['viewhandler' => function () {
    return ${($_ = isset($this->services['FOS\\RestBundle\\View\\ViewHandlerInterface']) ? $this->services['FOS\\RestBundle\\View\\ViewHandlerInterface'] : $this->load('getViewHandlerInterfaceService.php')) && false ?: '_'};
}]);
